---
abstract: 'Interface to test CSS string and file.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: '0'
  Test::Tester: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-CSS
no_index:
  directory:
    - t
    - inc
requires:
  File::Share: '0'
  File::ShareDir::Install: '0'
  JSON: '0'
  Test::Builder: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Manwar/Test-CSS.git
version: '0.01'
